### ISSUE TITLE
make_taxonomy returns binomials in taxa field when target_rank = 'subspecies'

### ISSUE THREAD

**Issue by Calamanthus** [Acanthiza/envClean#10]

**Comment by Acanthiza** [comment]
[11:08 AM] Allan, Joel (LandscapeSA)

This bit of the code suggests it should output whatever target rank you specify...

[11:08 AM] Allan, Joel (LandscapeSA)

        best <- tax_gbif %>%

          tidyr::pivot_longer(where(is.numeric), names_to = "key") %>%

          dplyr::mutate(key = purrr::map_chr(key

                                             , ~ gsub("Key"

                                                      , ""

                                                      , .

                                                      )

                                             )

                        ) %>%

          dplyr::filter(key %in% lurank$rank) %>%

          dplyr::left_join(lurank

                           , by = c("key" = "rank")

                           ) %>%

          dplyr::filter(sort <= target_sort) %>%

          dplyr::filter(sort == max(sort))

 

        tax_gbif$taxa <- best %>%

          dplyr::select(taxa = tolower(lurank$rank[lurank$sort == .$sort])) %>%

          dplyr::pull()

**Comment by Acanthiza** [comment]
So it looks like the results of `rgbif::taxonomy_backbone` don't include 'keys' below species level. So, it'll take some reworking to return subspecies. Looks like there may also be rgbif options now to do similar work: https://docs.ropensci.org/rgbif/articles/downloading_a_long_species_list.html to check out first (needs latest rgbif version)

**Comment by Calamanthus** [comment]
Interesting - I have seen that article and have been using rgbif::name_backbone_checklist to return a set of keys for a species list. I didn't realise this function was new, and assumed that your method using rgbif::taxonomy_backbone was superior...But, perhaps not now? rgbif::name_backbone_checklist is quite fast and could be combined with get_gbif_common/name_usage for the vernacular names...

Re the keys - the usageKey does denote lower taxonomic levels than species, although synonyms have different usage keys to the accepted. So, yes it would require reworking to integrate levels lower than species. Although, for synonyms there is an acceptedUsagekey that matches the accepted subspecies that could be used to join back to the accepted taxonomy and return a list of subspecies without too much extra effort? I can try this out and let you know if you like...

**Comment by Acanthiza** [comment]
If name_backbone_checklist is quick, a better workflow might be to just use that and then build the make_taxonomy results from that (the $raw part of make_taxonomy output would just be the outputs from name_backbone_checklist). Have to consider when/where to get common names in that workflow though. Either way it'll take a little work to retrieve results below species level as both only seem to return the taxonomic hierarchy to species level so there's no way to query on 'subspecies' in the same was as you can for any other level ('family', 'genus', 'species' etc). If you're able to try and get something working, that' be great as I won't get to this till next week probably.

**Comment by Calamanthus** [comment]
Yeah, name_backbone_checklist has a very similar output to the $raw, albeit with some slight differences. It will remain to be seen if there is any efficiency gain. 
I've extracted the accepted subspecies taxonomy for a small test list of ssp by using the acceptedUsageKey from name_backbone_checklist in name_usage, and then joining back to the original list. However, I haven't wrapped it in a broadly usable function yet or tested it on a larger dataset. 
I may not get to this till next week either, given this is just one step I'm employing in a complex process of extracting national range stats for all ssp of birds in the MLR. I'll see how I go.
